version: '3'

services:
  # Flask 应用服务
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "db"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_DATABASE: "test"
    depends_on:
      - db

  # MySQL 数据库服务
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    ports:
      - "3308:3306"
